// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mwdgrottngfmcelqydsg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im13ZGdyb3R0bmdmbWNlbHF5ZHNnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY3MzkxODgsImV4cCI6MjA3MjMxNTE4OH0.Jo9FgaHU_zEP3Fhgz8WTgF6diiMR7qkebmFCC1GjQOg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});